#!/bin/sh

set -e

if [ ! -f /usr/local/bin/brew ]; then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

if [ -f /usr/local/bin/peco ]; then
    echo 'peco already exists.'
else
   brew install peco 
fi